-- Create Reflections Table
create table if not exists reflections (
  id bigint generated by default as identity primary key,
  student_id uuid references auth.users not null,
  family_id bigint references families(id),
  phase text,
  content text,
  ai_feedback text,
  teacher_feedback text,
  grade text,
  status text default 'Pending',
  created_at timestamp with time zone default timezone('utc'::text, now())
);

-- Enable RLS
alter table reflections enable row level security;

-- Policies
create policy "Users can view their own reflections"
on reflections for select
to authenticated
using ( auth.uid() = student_id );

create policy "Users can insert their own reflections"
on reflections for insert
to authenticated
with check ( auth.uid() = student_id );

create policy "Teachers can view all reflections"
on reflections for select
to authenticated
using ( 
  exists (
    select 1 from profiles
    where profiles.id = auth.uid() and profiles.role = 'teacher'
  )
);

create policy "Teachers can update grading"
on reflections for update
to authenticated
using ( 
  exists (
    select 1 from profiles
    where profiles.id = auth.uid() and profiles.role = 'teacher'
  )
);
