import React, { useState, useEffect } from 'react';
import { Page, Text, View, Document, StyleSheet, PDFDownloadLink } from '@react-pdf/renderer';
import { supabase } from '../../services/supabaseClient';
import { useAuth } from '../../contexts/AuthContext';

// PDF Styles
const styles = StyleSheet.create({
    page: { flexDirection: 'column', backgroundColor: '#ffffff', padding: 30 },
    header: { marginBottom: 20, paddingBottom: 10, borderBottom: '1px solid #e2e8f0' },
    title: { fontSize: 20, textAlign: 'center', color: '#1e293b', marginBottom: 5, fontWeight: 'bold' },
    subtitle: { fontSize: 16, marginTop: 15, marginBottom: 8, color: '#334155', borderBottom: '1px solid #f1f5f9', paddingBottom: 2, fontWeight: 'bold' },
    text: { fontSize: 10, marginBottom: 4, lineHeight: 1.4, color: '#475569' },
    label: { width: 120, fontSize: 10, color: '#64748b', fontWeight: 'bold' },
    row: { flexDirection: 'row', marginBottom: 4 },
    value: { fontSize: 10, color: '#0f172a', flex: 1 },
    tableHeader: { flexDirection: 'row', backgroundColor: '#f8fafc', padding: 5, borderBottom: '1px solid #e2e8f0' },
    tableRow: { flexDirection: 'row', padding: 5, borderBottom: '1px solid #f1f5f9' },
    col1: { width: '25%' },
    col2: { width: '40%' },
    col3: { width: '35%' },
    footer: { position: 'absolute', bottom: 30, left: 30, right: 30, fontSize: 8, textAlign: 'center', color: '#94a3b8' }
});

// PDF Document Component
const FamilyReportDocument = ({ family, members, visits, studentName }) => (
    <Document>
        <Page size="A4" style={styles.page}>
            <View style={styles.header}>
                <Text style={styles.title}>Family Health Folder</Text>
                <Text style={{ fontSize: 10, textAlign: 'center', color: '#64748b' }}>Department of Community Medicine</Text>
            </View>

            <View style={{ marginBottom: 15 }}>
                <View style={styles.row}>
                    <Text style={styles.label}>Student Name:</Text>
                    <Text style={styles.value}>{studentName || 'Medical Student'}</Text>
                </View>
                <View style={styles.row}>
                    <Text style={styles.label}>Report Date:</Text>
                    <Text style={styles.value}>{new Date().toLocaleDateString()}</Text>
                </View>
            </View>

            <Text style={styles.subtitle}>Family Profile</Text>
            <View style={styles.row}>
                <Text style={styles.label}>Head of Family:</Text>
                <Text style={styles.value}>{family.head_name}</Text>
            </View>
            <View style={styles.row}>
                <Text style={styles.label}>Village/Location:</Text>
                <Text style={styles.value}>{family.village}</Text>
            </View>
            <View style={styles.row}>
                <Text style={styles.label}>Total Members:</Text>
                <Text style={styles.value}>{members.length}</Text>
            </View>
            {/* Note: SES Class would come from family.details if we implemented it */}

            <Text style={styles.subtitle}>Family Members</Text>
            <View style={styles.tableHeader}>
                <Text style={[styles.text, styles.col1, { fontWeight: 'bold' }]}>Name</Text>
                <Text style={[styles.text, styles.col1, { fontWeight: 'bold' }]}>Age/Gender</Text>
                <Text style={[styles.text, styles.col2, { fontWeight: 'bold' }]}>Relationship</Text>
            </View>
            {members.map((m, i) => (
                <View key={i} style={styles.tableRow}>
                    <Text style={[styles.text, styles.col1]}>{m.name}</Text>
                    <Text style={[styles.text, styles.col1]}>{m.age} / {m.gender}</Text>
                    <Text style={[styles.text, styles.col2]}>{m.relationship}</Text>
                </View>
            ))}

            <Text style={styles.subtitle}>Visit Logbook</Text>
            <View style={styles.tableHeader}>
                <Text style={[styles.text, styles.col1, { fontWeight: 'bold' }]}>Date</Text>
                <Text style={[styles.text, styles.col2, { fontWeight: 'bold' }]}>Activity</Text>
                <Text style={[styles.text, styles.col3, { fontWeight: 'bold' }]}>Notes</Text>
            </View>
            {visits.length === 0 ? (
                <Text style={[styles.text, { padding: 10, fontStyle: 'italic' }]}>No visits recorded yet.</Text>
            ) : (
                visits.map((v, i) => (
                    <View key={i} style={styles.tableRow}>
                        <Text style={[styles.text, styles.col1]}>{v.visit_date}</Text>
                        <Text style={[styles.text, styles.col2]}>{v.activity_type || 'General Visit'}</Text>
                        <Text style={[styles.text, styles.col3]}>{v.notes || '-'}</Text>
                    </View>
                ))
            )}

            <Text style={styles.footer}>
                Generated by FAP NextGen System | {new Date().getFullYear()}
            </Text>
        </Page>
    </Document>
);

const FamilyReportGenerator = () => {
    const { profile } = useAuth();
    const [families, setFamilies] = useState([]);
    const [selectedFamilyId, setSelectedFamilyId] = useState('');
    const [reportData, setReportData] = useState(null);
    const [loading, setLoading] = useState(false);

    useEffect(() => {
        if (profile) fetchFamilies();
    }, [profile]);

    useEffect(() => {
        if (selectedFamilyId) {
            prepareReport(selectedFamilyId);
        } else {
            setReportData(null);
        }
    }, [selectedFamilyId]);

    const fetchFamilies = async () => {
        const { data } = await supabase.from('families').select('*').eq('student_id', profile.id);
        setFamilies(data || []);
    };

    const prepareReport = async (famId) => {
        setLoading(true);
        try {
            const family = families.find(f => f.id === famId);

            const { data: members } = await supabase.from('family_members').select('*').eq('family_id', famId);
            const { data: visits } = await supabase.from('family_visits').select('*').eq('family_id', famId).order('visit_date', { ascending: false });

            setReportData({
                family,
                members: members || [],
                visits: visits || [],
                studentName: profile.full_name || profile.email
            });
        } catch (err) {
            console.error(err);
        } finally {
            setLoading(false);
        }
    };

    return (
        <div className='tool-card'>
            <h3>Generate Reports</h3>
            <p style={{ fontSize: '0.9rem', color: '#666', marginBottom: '1rem' }}>
                Download standardized PDF reports for your logbook or department submission.
            </p>

            <div style={{ marginBottom: '1rem' }}>
                <select
                    className="form-control"
                    value={selectedFamilyId}
                    onChange={e => setSelectedFamilyId(e.target.value)}
                    style={{ width: '100%', padding: '0.5rem', borderRadius: '4px', border: '1px solid #cbd5e1' }}
                >
                    <option value="">Select Family for Report...</option>
                    {families.map(f => (
                        <option key={f.id} value={f.id}>{f.head_name} - {f.village}</option>
                    ))}
                </select>
            </div>

            <div style={{ display: 'flex', gap: '1rem' }}>
                {selectedFamilyId && reportData && !loading ? (
                    <PDFDownloadLink
                        document={<FamilyReportDocument {...reportData} />}
                        fileName={`FAP_Report_${reportData.family.head_name.replace(/\s+/g, '_')}.pdf`}
                    >
                        {({ blob, url, loading: pdfLoading, error }) =>
                            <button style={btnStyle} disabled={pdfLoading}>
                                {pdfLoading ? 'Building PDF...' : 'Download Family Folder PDF'}
                            </button>
                        }
                    </PDFDownloadLink>
                ) : (
                    <button style={{ ...btnStyle, opacity: 0.5, cursor: 'not-allowed' }} disabled>
                        {loading ? 'Fetching Data...' : 'Select a Family to Generate'}
                    </button>
                )}
            </div>
        </div>
    );
};

const btnStyle = {
    backgroundColor: 'var(--color-primary)',
    color: 'white',
    padding: '0.75rem 1rem',
    border: 'none',
    borderRadius: '0.5rem',
    cursor: 'pointer',
    fontWeight: '600',
    display: 'flex',
    alignItems: 'center',
    gap: '0.5rem',
    fontSize: '0.95rem'
};

export default FamilyReportGenerator;
