import React from 'react';
import { Page, Text, View, Document, StyleSheet, PDFDownloadLink } from '@react-pdf/renderer';

// Create styles
const styles = StyleSheet.create({
    page: {
        flexDirection: 'column',
        backgroundColor: '#ffffff',
        padding: 30,
    },
    section: {
        margin: 10,
        padding: 10,
        flexGrow: 1,
    },
    title: {
        fontSize: 24,
        marginBottom: 20,
        textAlign: 'center',
        color: '#1e293b'
    },
    subtitle: {
        fontSize: 18,
        marginBottom: 10,
        marginTop: 20,
        color: '#334155',
        borderBottom: '1px solid #e2e8f0',
        paddingBottom: 5
    },
    text: {
        fontSize: 12,
        marginBottom: 5,
        lineHeight: 1.5,
        color: '#475569'
    },
    row: {
        flexDirection: 'row',
        marginBottom: 5,
    },
    label: {
        width: 100,
        fontWeight: 'bold',
        fontSize: 12,
        color: '#64748b'
    },
    value: {
        fontSize: 12,
        color: '#0f172a'
    }
});

// Create Document Component
const MyDocument = () => (
    <Document>
        <Page size="A4" style={styles.page}>
            <View style={styles.section}>
                <Text style={styles.title}>Family Health Report</Text>

                <Text style={styles.text}>Date: {new Date().toLocaleDateString()}</Text>
                <Text style={styles.text}>Student: MBBS Student Name</Text>

                <Text style={styles.subtitle}>Family Profile</Text>
                <View style={styles.row}>
                    <Text style={styles.label}>Family Head:</Text>
                    <Text style={styles.value}>Ramesh Kumar</Text>
                </View>
                <View style={styles.row}>
                    <Text style={styles.label}>Location:</Text>
                    <Text style={styles.value}>Village A, District B</Text>
                </View>
                <View style={styles.row}>
                    <Text style={styles.label}>SES Class:</Text>
                    <Text style={styles.value}>Upper Lower (IV)</Text>
                </View>

                <Text style={styles.subtitle}>Health Summary</Text>
                <Text style={styles.text}>
                    Based on the recent visits, the family faces challenges related to sanitation and seasonal viral fevers.
                    Hypertension management for the head of the family is ongoing with fair compliance.
                </Text>

                <Text style={styles.subtitle}>Recommendations</Text>
                <Text style={styles.text}>1. Continue monthly BP monitoring.</Text>
                <Text style={styles.text}>2. Nutrition counseling for anemia prevention.</Text>
                <Text style={styles.text}>3. Ensure water chlorination during monsoon.</Text>

                <Text style={{ position: 'absolute', bottom: 30, left: 30, right: 30, fontSize: 10, textAlign: 'center', color: '#94a3b8' }}>
                    Generated by FAP NextGen | Department of Community Medicine
                </Text>
            </View>
        </Page>
    </Document>
);

const FamilyReportGenerator = () => (
    <div className='tool-card'>
        <h3>Generate Reports</h3>
        <p style={{ fontSize: '0.9rem', color: '#666', marginBottom: '1rem' }}>
            Download standardized PDF reports for your logbook or department submission.
        </p>
        <div style={{ display: 'flex', gap: '1rem', marginTop: '1rem' }}>
            <PDFDownloadLink document={<MyDocument />} fileName="family_report.pdf">
                {({ blob, url, loading, error }) =>
                    loading ? (
                        <button style={btnStyle} disabled>Loading Document...</button>
                    ) : (
                        <button style={btnStyle}>Download Family Folder PDF</button>
                    )
                }
            </PDFDownloadLink>
        </div>
    </div>
);

const btnStyle = {
    backgroundColor: 'var(--color-primary)',
    color: 'white',
    padding: '0.75rem 1rem',
    border: 'none',
    borderRadius: '0.5rem',
    cursor: 'pointer',
    fontWeight: '600',
    display: 'flex',
    alignItems: 'center',
    gap: '0.5rem',
    fontSize: '0.95rem'
};

export default FamilyReportGenerator;
